[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/=lib/chainlink-local/",
    "@ccip/contracts=lib/chainlink-local/lib/ccip/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
rpc_endpoints = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/wHEFFjcDt1xkPRjzDZycgAsnKWk1GHcK", arb-sepolia = "https://arb-sepolia.g.alchemy.com/v2/wHEFFjcDt1xkPRjzDZycgAsnKWk1GHcK"}
# via-ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
